# Generated by Django 5.0.2 on 2024-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="members",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
